version: '3'
services:
  worker:
    image: rodrigorootrj/service:sql-playground-1.42.01              
    environment:
      - DB_USR:${DB_USR}
      - DB_HOST:${DB_HOST}
      - DB_PASS:${DB_PASS}
      - DB_NAME:${DB_NAME}
    volumes:
      - type: bind
        source: ./src
        target: /app/
    command: python /app/work.py

  db_host:
    image: mysql:8.4.2
    restart: always
    environment:
      - MYSQL_USER=${DB_USR}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - 6000:3306
    volumes:
      - db_volume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db_host

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana



volumes:
  db_volume:
  grafana:   
####Debug###
  # busybox:
  #   image: busybox
  #   restart: always
  #   command: tail -f /dev/null       